#!/bin/bash
# Clone all pykit3 package repositories into packages/ directory
# Reads repo names from docs/repos.txt (generated by workspace-build-repo-list.py)

set -e

cd "$(dirname "$0")"

if [ ! -f docs/repos.txt ]; then
    echo "docs/repos.txt not found. Run scripts/workspace-build-repo-list.py first."
    exit 1
fi

mkdir -p packages
cd packages

while read -r name; do
    [ -z "$name" ] && continue
    if [ -d "$name" ]; then
        echo "[$name] exists, skip"
    else
        echo "[$name] cloning..."
        git clone "git@github.com:pykit3/${name}.git"
    fi
done < ../docs/repos.txt

echo "Done!"
